name: Build Images

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request_target:
    types: [labeled]
  workflow_dispatch: {}

jobs:
  build-core-images:
    runs-on: ubuntu-24.04-arm
    if: >
      contains(github.event.pull_request.labels.*.name, 'dependencies')
      || github.event_name == 'push'
      || github.event_name == 'workflow_dispatch'
    permissions:
      packages: write
      contents: read
    timeout-minutes: 20
    steps:
      - name: Set PWD environment variable
        run: echo "PWD=$(pwd)" >> $GITHUB_ENV

      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.10.0
        with:
          install: true

      - name: Authenticate with  GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v6.5.0
        with:
          pull: true
          push: ${{ github.ref == 'refs/heads/main' }}
          files: core/noble/docker-bake.hcl
          source: .
          set: |
            *.cache-from=type=gha,scope=core/noble
            *.cache-to=type=gha,scope=core/noble,mode=max
            *.platform=linux/arm64
